#!/bin/bash

set -ex

echo "Installing consul server on $JUJU_UNIT_NAME"

TGT_DIR=/usr/local/bin


bzip2 -k -c -d $CHARM_DIR/files/consul.amd64.bz2 > $TGT_DIR/consul
chmod 555 $TGT_DIR/consul

groupadd consul
useradd -d /var/lib/consul \
    -g consul \
    -s /sbin/nologin \
    --system \
    consul

mkdir /var/lib/consul
chown consul: /var/lib/consul

mkdir /usr/share/consul
chown consul: /usr/share/consul

tar xzv -C /usr/share/consul -f $CHARM_DIR/files/web_ui.tgz

install -m 0644 $CHARM_DIR/files/consul.upstart /etc/init/consul.conf
